# Generated by Django 6.0.5 on 2026-05-21 18:59

import django.core.validators
import django.db.models.deletion
import fernet_fields.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(help_text='Полное юридическое название организации', max_length=255, verbose_name='Название компании')),
                ('status', models.CharField(choices=[('pending', 'На модерации'), ('active', 'Активен'), ('blocked', 'Заблокирован')], default='pending', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email для входа')),
                ('membership_category', models.CharField(choices=[('veteran', 'Ветеран (физ. лицо, пожизненно)'), ('partner_veteran', 'Партнёр-ветеран (юридическое лицо)'), ('partner_support', 'Партнёр-поддержка (юридическое лицо)'), ('associate_partner', 'Ассоциированный партнёр (юридическое лицо)')], default='associate_partner', max_length=30, verbose_name='Категория членства')),
                ('annual_revenue', models.DecimalField(blank=True, decimal_places=2, help_text='Для расчёта членского взноса', max_digits=15, null=True, verbose_name='Годовой оборот (руб.)')),
                ('provides_support', models.BooleanField(default=False, verbose_name='Оказывает поддержку ветеранам')),
                ('inn', fernet_fields.fields.EncryptedCharField(help_text='Идентификационный номер налогоплательщика (10 или 12 цифр)', max_length=12, verbose_name='ИНН')),
                ('ogrn', fernet_fields.fields.EncryptedCharField(help_text='Основной государственный регистрационный номер (13 или 15 цифр)', max_length=15, verbose_name='ОГРН')),
                ('legal_address', fernet_fields.fields.EncryptedCharField(max_length=500, verbose_name='Юридический адрес')),
                ('actual_address', fernet_fields.fields.EncryptedCharField(blank=True, help_text='Если не указан, совпадает с юридическим', max_length=500, null=True, verbose_name='Фактический адрес')),
                ('director_fullname', fernet_fields.fields.EncryptedCharField(max_length=255, verbose_name='ФИО директора')),
                ('phone', fernet_fields.fields.EncryptedCharField(max_length=20, verbose_name='Телефон')),
                ('agreement_signed', models.BooleanField(default=False, verbose_name='Согласие на обработку ПДн')),
                ('agreement_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата согласия')),
                ('next_payment_date', models.DateField(blank=True, null=True, verbose_name='Дата следующего платежа')),
                ('charter_document', models.FileField(blank=True, help_text='Загрузите устав организации в формате PDF', null=True, upload_to='documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'], message='Поддерживаются только PDF, JPG и PNG файлы'), django.core.validators.MaxValueValidator(5242880, message='Размер файла не должен превышать 5 МБ')], verbose_name='Устав организации (PDF)')),
                ('ogrn_document', models.FileField(blank=True, help_text='Свидетельство о государственной регистрации', null=True, upload_to='documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'], message='Поддерживаются только PDF, JPG и PNG файлы'), django.core.validators.MaxValueValidator(5242880, message='Размер файла не должен превышать 5 МБ')], verbose_name='Свидетельство ОГРН (PDF)')),
                ('inn_document', models.FileField(blank=True, help_text='Свидетельство о постановке на учет в налоговом органе', null=True, upload_to='documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'], message='Поддерживаются только PDF, JPG и PNG файлы'), django.core.validators.MaxValueValidator(5242880, message='Размер файла не должен превышать 5 МБ')], verbose_name='Свидетельство ИНН (PDF)')),
                ('additional_document', models.FileField(blank=True, help_text='Любые дополнительные документы', null=True, upload_to='documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'], message='Поддерживаются только PDF, JPG и PNG файлы'), django.core.validators.MaxValueValidator(5242880, message='Размер файла не должен превышать 5 МБ')], verbose_name='Дополнительный документ (PDF)')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Член ассоциации',
                'verbose_name_plural': 'Члены ассоциации',
                'ordering': ['-created_at'],
            },
        ),
    ]
