# Generated by Django 6.0.5 on 2026-05-21 19:16

import django.core.validators
import members.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='additional_document',
            field=models.FileField(blank=True, help_text='Любые дополнительные документы', null=True, upload_to='documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'], message='Поддерживаются только PDF, JPG и PNG файлы'), members.models.validate_file_size], verbose_name='Дополнительный документ (PDF)'),
        ),
        migrations.AlterField(
            model_name='member',
            name='charter_document',
            field=models.FileField(blank=True, help_text='Загрузите устав организации в формате PDF', null=True, upload_to='documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'], message='Поддерживаются только PDF, JPG и PNG файлы'), members.models.validate_file_size], verbose_name='Устав организации (PDF)'),
        ),
        migrations.AlterField(
            model_name='member',
            name='inn_document',
            field=models.FileField(blank=True, help_text='Свидетельство о постановке на учет в налоговом органе', null=True, upload_to='documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'], message='Поддерживаются только PDF, JPG и PNG файлы'), members.models.validate_file_size], verbose_name='Свидетельство ИНН (PDF)'),
        ),
        migrations.AlterField(
            model_name='member',
            name='ogrn_document',
            field=models.FileField(blank=True, help_text='Свидетельство о государственной регистрации', null=True, upload_to='documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'], message='Поддерживаются только PDF, JPG и PNG файлы'), members.models.validate_file_size], verbose_name='Свидетельство ОГРН (PDF)'),
        ),
    ]
